name: fasting_timer
description: "Simple intermittent fasting tracker with widgets"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Local DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Timer & notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Ads
  google_mobile_ads: ^5.3.0

  # UI
  fl_chart: ^0.69.2

  # Widgets (native bridge)
  home_widget: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
